# Generated by Django 2.2 on 2021-10-11 15:41

from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0002_auto_20200822_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, default='', help_text='1280x720px', upload_to='playlist_thumbnail/%H/%M')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Playlist Kategorie',
                'verbose_name_plural': 'Playlist Kategorien',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, choices=[('daniel', 'Daniel Jung'), ('max', 'Max Metelmann'), ('kai', 'Lehrer Schmidt'), ('rieke', 'Rieke Strehl')], default='daniel', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, default='', help_text='1280x720px', upload_to='video-thumbnail/%H/%M')),
                ('youtube_hash', models.CharField(blank=True, default='', max_length=20)),
                ('file', models.FileField(upload_to='videos/%H/%M', verbose_name='Video MP4 Datei')),
                ('original_size', models.FileField(blank=True, default='', upload_to='videos/%H/%M', verbose_name='Video MP4 Datei (ORIGINAL SIZE)')),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='video.Playlist')),
                ('playlists', models.ManyToManyField(blank=True, related_name='playlist_videos', to='video.Playlist')),
                ('tags', models.ManyToManyField(related_name='videos_in_tag', to='hashtag.HashTag')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='video.PlaylistCategory'),
        ),
    ]
