# Generated by Django 2.2 on 2021-10-19 09:18

from django.db import migrations, models
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20211019_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='idate',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='udate',
        ),
        migrations.RemoveField(
            model_name='playlistcategory',
            name='idate',
        ),
        migrations.RemoveField(
            model_name='playlistcategory',
            name='udate',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='idate',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='udate',
        ),
        migrations.RemoveField(
            model_name='video',
            name='idate',
        ),
        migrations.RemoveField(
            model_name='video',
            name='udate',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='hash_id',
            field=models.CharField(default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='playlistcategory',
            name='hash_id',
            field=models.CharField(default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hash_id',
            field=models.CharField(default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='hash_id',
            field=models.CharField(default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30),
        ),
    ]
