# Generated by Django 2.2 on 2021-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20211019_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos_in_tag', to='video.Tag'),
        ),
    ]
