# Generated by Django 2.2 on 2021-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20211019_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_size',
            field=models.FileField(blank=True, default='', upload_to='videos-orig/%H/%M', verbose_name='Video MP4 Datei (ORIGINAL SIZE)'),
        ),
    ]
