# Generated by Django 2.1.1 on 2020-08-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_squashed_0063_auto_20200728_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_tutor_pings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
