# Generated by Django 2.1.1 on 2020-11-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_question_number_tutor_pings'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved_with_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
