# Generated by Django 2.2 on 2020-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_solved_with_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_acted_user_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='question',
            name='last_acted_user_username',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='question',
            name='last_acted_user_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='tag_names',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
