# Generated by Django 2.2 on 2020-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201209_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
