# Generated by Django 2.2 on 2020-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20201209_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='vote_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='vote_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
