# Generated by Django 2.2 on 2021-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20201217_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_first_question',
            field=models.BooleanField(default=False),
        ),
    ]
