# Generated by Django 2.2 on 2021-01-25 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question_is_first_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solved_with_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helped_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
