# Generated by Django 2.2 on 2021-02-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20210216_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
    ]
