# Generated by Django 2.2 on 2021-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_question_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
