# Generated by Django 2.2 on 2021-03-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_question_off_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='off_hash',
        ),
    ]
