# Generated by Django 2.2 on 2021-07-13 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0016_remove_question_off_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
