# Generated by Django 5.2.12 on 2026-09-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20210713_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number_tutor_pings',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solved_with_tutor',
        ),
    ]
