# Generated by Django 5.2.17 on 2026-09-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_remove_question_tutor_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionInvolvedUsers',
        ),
    ]
