# Generated by Django 2.2 on 2021-07-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0002_auto_20200822_0345'),
        ('question', '0017_auto_20210713_1112'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('text', models.TextField()),
                ('relation_source', models.CharField(blank=True, choices=[('helper', 'Hat mir geholfen'), ('worked_together', 'Zusammen gearbeitet'), ('studied_together', 'Zusammen studiert')], default='', max_length=50)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_user_reviews', to=settings.AUTH_USER_MODEL)),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reviews', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(related_name='user_review_hashtags', to='hashtag.HashTag')),
                ('source_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews_from_question', to='question.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
