# Generated by Django 2.2 on 2021-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='is_happy',
            field=models.BooleanField(default=False),
        ),
    ]
