# Generated by Django 2.1.1 on 2020-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_squashed_0009_auto_20200405_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
