version: '3.1'

networks:
  nl-net:
     external: true

services:

  db:
    image: postgres
    restart: always
    volumes:
      - /var/dockerfiles/swarm/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: S0m3G00dPa55W0rdThi5i5
    ports:
      - "5432:5432"
    networks:
       - nl-net

