# Generated by Django 2.1.1 on 2020-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionview',
            name='source_ip',
            field=models.GenericIPAddressField(db_index=True, default='192.168.0.1'),
        ),
    ]
