# Generated by Django 2.1.1 on 2020-04-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0001_squashed_0018_auto_20200708_2033'),
        ('stats', '0002_auto_20200317_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True, default='192.168.0.1')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_views', to='playlist.Playlist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_playlist_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
