# Generated by Django 2.2 on 2020-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_playlistview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('percent_answered', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('unanswered_questions', models.IntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
            ],
        ),
    ]
