# Generated by Django 2.2 on 2021-08-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_globalstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstats',
            name='percent_answered',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
