# Generated by Django 2.1.1 on 2020-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_squashed_0018_auto_20200708_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='int_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
