# Generated by Django 2.1.1 on 2020-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_unit_int_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='int_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
