# Generated by Django 2.1.1 on 2020-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20201202_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='order',
        ),
    ]
