# Generated by Django 2.1.1 on 2020-09-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorping',
            old_name='target_user',
            new_name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorping',
            name='ready_to_pay',
        ),
    ]
