# Generated by Django 2.1.1 on 2020-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_tutorsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
