# Generated by Django 2.1.1 on 2020-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_tutorsetting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorping',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
