# Generated by Django 2.1.1 on 2020-09-01 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0005_tutorping_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('paypal_order_id', models.CharField(default='', max_length=50)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('voucher_file', models.FileField(blank=True, default='', help_text='Nutzer kann seine Rechnungen später im Profil herunterladen', upload_to='payment_voucher/', verbose_name='Rechnung (PDF)')),
                ('tutor_ping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_payment', to='tutoring.TutorPing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='half_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='ninety_min_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
