# Generated by Django 2.1.1 on 2020-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20200901_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorping',
            name='needed_time',
            field=models.IntegerField(default=30),
        ),
    ]
