# Generated by Django 2.1.1 on 2020-09-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_tutorping_needed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='users_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
