# Generated by Django 2.1.1 on 2020-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_auto_20200902_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='target_group',
            field=models.TextField(default=''),
        ),
    ]
