# Generated by Django 2.1.1 on 2020-10-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_auto_20201028_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tutor_ping',
            new_name='request',
        ),
    ]
