# Generated by Django 2.1.1 on 2020-10-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_auto_20201028_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
