# Generated by Django 2.1.1 on 2020-10-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_helprequest_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='last_acted_side',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
