# Generated by Django 2.1.1 on 2020-10-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0014_helprequest_last_acted_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='last_acted_side',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='last_acted_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
