# Generated by Django 2.1.1 on 2020-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_auto_20201029_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
