# Generated by Django 2.1.1 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_helprequest_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='per_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
