# Generated by Django 2.1.1 on 2020-10-30 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0017_helprequest_per_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('paid_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_payout_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tutorsetting',
            name='target_group',
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='payment_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', 'Zahlungsart auswählen'), ('paypal', 'PayPal'), ('iban', 'IBAN')], max_length=20),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='paypal_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='sek_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='sek_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='uni',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
