# Generated by Django 2.1.1 on 2020-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_auto_20201030_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='invoice_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
