# Generated by Django 2.1.1 on 2020-11-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0019_payoutrequest_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorsetting',
            name='uni',
        ),
        migrations.AddField(
            model_name='tutorsetting',
            name='university_modules',
            field=models.TextField(default=''),
        ),
    ]
