# Generated by Django 2.1.1 on 2020-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0020_auto_20201101_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('', 'Zahlungsart auswählen'), ('paypal', 'PayPal'), ('iban', 'Überweisung')], max_length=20),
        ),
    ]
