# Generated by Django 2.1.1 on 2020-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0021_auto_20201101_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='payment_changed_to',
            field=models.CharField(blank=True, choices=[('paypal', 'Paypal'), ('iban', 'IBAN')], default='', max_length=10),
        ),
    ]
