# Generated by Django 2.1.1 on 2020-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0022_tutorsetting_payment_changed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='payment_confirm_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
