# Generated by Django 2.1.1 on 2020-11-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0023_tutorsetting_payment_confirm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_help_requests', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_help_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='payment_changed_to',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('iban', 'Überweisung')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutorsetting',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('iban', 'Überweisung')], max_length=20),
        ),
    ]
