# Generated by Django 2.1.1 on 2020-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0024_auto_20201102_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('paid', 'Ausgezahlt')], default='', max_length=20),
        ),
    ]
