# Generated by Django 2.1.1 on 2020-11-02 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0025_payoutrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payout_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
