# Generated by Django 2.1.1 on 2020-11-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0026_auto_20201102_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='date_time',
            new_name='date_time1',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='date_time2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='date_time3',
            field=models.DateTimeField(null=True),
        ),
    ]
