# Generated by Django 2.1.1 on 2020-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0027_auto_20201109_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='accepted_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
