# Generated by Django 2.1.1 on 2020-11-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0029_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=True, help_text='Wenn aktiv, ist die Bewertung öffentlich.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_reviews', to='tutoring.HelpRequest'),
        ),
    ]
