# Generated by Django 2.1.1 on 2020-11-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0033_auto_20201124_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='tutor_profile_video/%Y/%m/'),
        ),
    ]
