# Generated by Django 2.1.1 on 2020-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0034_tutorsetting_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsetting',
            name='video_thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='tutor_video_thumbnail/%Y/%m/'),
        ),
    ]
