# Generated by Django 2.1.1 on 2020-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0036_remove_tutorsetting_video_thumbnail'),
        ('tutoring', '0034_helprequest_users_share'),
    ]

    operations = [
    ]
