# Generated by Django 2.2 on 2021-01-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0038_helprequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='declined_at',
            field=models.DateTimeField(null=True),
        ),
    ]
