# Generated by Django 2.2 on 2021-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0039_auto_20210130_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
