# Generated by Django 2.2 on 2021-03-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0040_auto_20210201_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': ('idate',)},
        ),
    ]
