# Generated by Django 2.2 on 2021-06-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0041_auto_20210304_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={'verbose_name': 'Nachhilfe Session', 'verbose_name_plural': 'Nachhilfe Sessions'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Zahlung', 'verbose_name_plural': 'Zahlungen'},
        ),
        migrations.AlterModelOptions(
            name='payoutrequest',
            options={'verbose_name': 'Auszahlung', 'verbose_name_plural': 'Auszahlungen'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Bewertung', 'verbose_name_plural': 'Bewertungen'},
        ),
        migrations.AlterModelOptions(
            name='tutorsetting',
            options={'verbose_name': 'Tutor Profil', 'verbose_name_plural': 'Tutor Profile'},
        ),
    ]
