# Generated by Django 5.2.12 on 2026-09-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0042_auto_20210629_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='request',
        ),
        migrations.RemoveField(
            model_name='review',
            name='request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='given_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorsetting',
            name='user',
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PayoutRequest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TutorSetting',
        ),
    ]
