# Generated by Django 2.1.1 on 2020-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, default='192.168.0.1')),
                ('idate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
