# Generated by Django 2.1.1 on 2020-08-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0063_remove_profile_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
    ]
