# Generated by Django 2.1.1 on 2020-08-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200805_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='relation_source',
            field=models.CharField(blank=True, choices=[('helper', 'Hat mir geholfen'), ('worked_together', 'Zusammen gearbeitet'), ('studied_together', 'Zusammen studiert')], default='', max_length=50),
        ),
    ]
