# Generated by Django 2.1.1 on 2020-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_filled_data_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skipped_data_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
