# Generated by Django 2.1.1 on 2020-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_skipped_data_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(blank=True, choices=[('schule', 'Schule'), ('uni', 'Uni')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
