# Generated by Django 2.1.1 on 2020-08-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200825_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answered_month',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='answered_week',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='answers_this_month',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='answers_this_week',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_answers',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
