# Generated by Django 2.1.1 on 2020-09-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tutorsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorsetting',
            name='user',
        ),
        migrations.DeleteModel(
            name='TutorSetting',
        ),
    ]
