# Generated by Django 2.1.1 on 2020-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200901_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
