# Generated by Django 2.1.1 on 2020-09-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_can_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_tutor',
            field=models.BooleanField(default=False, verbose_name='Kann Nachhilfeunterricht geben'),
        ),
    ]
