# Generated by Django 2.1.1 on 2020-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200901_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_tutored',
            field=models.IntegerField(default=0),
        ),
    ]
