# Generated by Django 2.1.1 on 2020-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_total_tutored'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
