# Generated by Django 2.1.1 on 2020-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Wenn zum ersten Mal aktiviert, erhält User eine E-Mail Benachrichtung.'),
        ),
    ]
