# Generated by Django 2.1.1 on 2020-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200916_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_questions',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
