# Generated by Django 2.1.1 on 2020-11-05 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_profile_total_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(blank=True, max_length=1024)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(blank=True, default='', max_length=1024)),
                ('country', models.CharField(blank=True, choices=[('de', 'Deutschland'), ('at', 'Österreich'), ('ch', 'Schweiz')], default='de', max_length=1024)),
                ('type', models.CharField(choices=[('invoice', 'Rechnungsadresse'), ('postal', 'lieferadresse')], default='invoice', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
