# Generated by Django 2.2 on 2020-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201130_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='most_helped_tags',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
