# Generated by Django 2.2 on 2021-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20201214_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_asks',
            field=models.IntegerField(default=0),
        ),
    ]
