# Generated by Django 2.2 on 2021-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_profile_number_asks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='helper_detected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
