# Generated by Django 2.2 on 2021-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profile_helper_detected_at'),
    ]

    operations = [
        # Das Review-Modell ist in die review-App umgezogen. Nur aus dem State
        # der user-App entfernen — die physische `user_review`-Tabelle bleibt
        # erhalten (sie wird jetzt vom Review-Modell der review-App genutzt).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Review',
                ),
            ],
            database_operations=[],
        ),
    ]
