# Generated by Django 2.2 on 2021-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profile_helper_detected_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
