# Generated by Django 5.2.12 on 2026-03-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='synced',
        ),
    ]
