# Generated by Django 5.2.12 on 2026-09-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_drop_legacy_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_tutor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_tutored',
        ),
    ]
