# Generated by Django 5.2.17 on 2026-09-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_profile_tutor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fcm_token',
        ),
    ]
