# Generated by Django 2.2 on 2021-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
