version: '3'
networks:
  nl-net:
    external: true
services:
  informatikfragen-server:
    container_name: informatikfragen-server
    image: registry.gitlab.com/new-learning/mathefragen.de/app:latest
    volumes:
      - /var/www/aiedn/apps/mathefragen.de/.env.informatik:/code/.env
      - /var/log/aiedn/informatikfragen.de/log:/code/log
    environment:
      - TZ=Europe/Berlin
    restart: always
    networks:
      - nl-net
