# Generated by Django 2.1.1 on 2020-08-05 19:04

from django.db import migrations, models
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_squashed_0063_auto_20200728_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='question_hashtags', to='question.Question')),
                ('subtags', models.ManyToManyField(blank=True, related_name='_hashtag_subtags_+', to='hashtag.HashTag', verbose_name='Sub-Tags')),
                ('is_main_tag', models.BooleanField(default=False, verbose_name='Haupt-Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
