# Generated by Django 2.1.1 on 2020-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_squashed_0008_auto_20200523_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question_hashtags', to='question.Question'),
        ),
    ]
