# Generated by Django 5.2.17 on 2026-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_auto_20200822_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='subtags',
            field=models.ManyToManyField(blank=True, to='hashtag.hashtag', verbose_name='Sub-Tags'),
        ),
    ]
