# Generated by Django 2.1.1 on 2020-08-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mathefragen.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, default=mathefragen.apps.core.models.create_default_hash, editable=False, max_length=30)),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_news', to=settings.AUTH_USER_MODEL)),
                ('is_update', models.BooleanField(default=False, help_text='Wenn es ein Applikation-Update ist')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikeln',
            },
        ),
        migrations.CreateModel(
            name='ReadReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idate', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.News')),
                ('public', models.BooleanField(default=False)),
                ('version', models.CharField(default='', help_text='e.g. 1.0.0, 1.1.0, 1.1.1', max_length=50)),
                ('public_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Release Note',
                'verbose_name_plural': 'Release Notes',
            },
            bases=('news.news',),
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_update',
        ),
        migrations.AddField(
            model_name='readreleasenote',
            name='release_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_release_notes', to='news.ReleaseNote'),
        ),
        migrations.AddField(
            model_name='readreleasenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_read_release_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
