# Generated by Django 2.1.1 on 2020-08-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='footer_img/')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='settings.FooterColumn')),
                ('open_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Footer Reihe',
                'verbose_name_plural': 'Footer Reihe',
            },
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(help_text='Ja: PNG, JPG, JPEG, SVG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/logo/')),
                ('ci_color', models.CharField(default='#03689e', help_text='CI Farbe als Hex Code', max_length=50)),
                ('question_editor', models.CharField(choices=[('tiny', 'TinyMCE'), ('md', 'Markdown')], default='tiny', max_length=20)),
                ('logo_icon', models.FileField(blank=True, default='', help_text='Ja: PNG, JPG, JPEG, SVG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/logo/icon/')),
                ('slogan', models.TextField(blank=True, default='', help_text='Dieser Text erscheint in Registrierung- & Loginseiten.')),
                ('sign_background_image', models.ImageField(blank=True, default='', help_text='Ja: PNG, JPG, JPEG, SVG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/bg/')),
            ],
            options={
                'verbose_name': 'Globale Einstellung',
                'verbose_name_plural': 'Globale Einstellung',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='', max_length=100)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.HeaderMenu')),
            ],
            options={
                'verbose_name': 'Header Sub-Menü',
                'verbose_name_plural': 'Header Sub-Menü',
            },
        ),
        migrations.CreateModel(
            name='RecommendedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(help_text='Ja: PNG, JPG, JPEG, SVG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/recommended_by/')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Empfohlen von (im Header)',
                'verbose_name_plural': 'Empfohlen von (im Header)',
            },
        ),
        migrations.CreateModel(
            name='AppPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_app_link', models.CharField(blank=True, default='', max_length=500)),
                ('android_app_link', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='mathefragen.de - Fragen. Teilen. Helfen.', max_length=200)),
                ('meta_description', models.CharField(blank=True, default='Wo Schüler & Studenten Mathe verstehen.', max_length=200)),
                ('share_image', models.ImageField(blank=True, default='', upload_to='project/share-img/')),
                ('fb_app_id', models.CharField(blank=True, default='359857967960662', help_text='Facebook App ID', max_length=100)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('embed_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code Snippets (e.g. Google Analytics)',
                'verbose_name_plural': 'Code Snippets (e.g. Google Analytics)',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_3_days', models.BooleanField(default=True, help_text='Hauptfeed zeigt nur Content der letzten 3 Tage')),
            ],
            options={
                'verbose_name': 'Performance Settings',
                'verbose_name_plural': 'Performance Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='footercolumn',
            options={'verbose_name': 'Footer Spalte', 'verbose_name_plural': 'Footer Spalte'},
        ),
        migrations.AlterModelOptions(
            name='headermenu',
            options={'verbose_name': 'Header-Menü', 'verbose_name_plural': 'Header-Menü'},
        ),
    ]
