# Generated by Django 2.2 on 2020-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_squashed_0013_auto_20200805_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='sign_background_image',
        ),
        migrations.AddField(
            model_name='global',
            name='logo_icon_svg_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='global',
            name='logo_svg_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='global',
            name='logo',
            field=models.FileField(help_text='Ja: PNG, JPG, JPEG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/logo/'),
        ),
        migrations.AlterField(
            model_name='global',
            name='logo_icon',
            field=models.FileField(blank=True, default='', help_text='Ja: PNG, JPG, JPEG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/logo/icon/'),
        ),
    ]
