# Generated by Django 2.2 on 2020-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201225_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='logo',
            field=models.FileField(blank=True, default='', help_text='Ja: PNG, JPG, JPEG... Nein: PDF, MP4 und alles was kein Logo sein kann.', upload_to='project/logo/'),
        ),
    ]
