version: '3'
networks:
  nl-net:
    external: true
services:
  biofragen-server:
    container_name: biofragen-server
    image: registry.gitlab.com/new-learning/mathefragen.de/app:latest
    volumes:
      - /var/www/aiedn/apps/mathefragen.de/.env.bio.api:/code/.env
      - /var/log/aiedn/api.bio.aiedn.com/log:/code/log
    environment:
      - TZ=Europe/Berlin
    restart: always
    networks:
      - nl-net
